### PR TITLE
fix: conflict with TypeScript import, updated package.json

### PR DESCRIPTION
**Pull request by P3DR0DEV**
…/index.d.ts

## Related Issues
[Link to the issue](https://github.com/Splidejs/react-splide/issues/72)

## Description

Just added the export types to the package.json

### CODE REVIEW

**Review by arturmoroz — APPROVED** [review]

**Review by chussum — APPROVED** [review]

**Comment by knirb** [comment]
Any reason why this is not merged yet? It's pretty annoying to not be able to use this lib without forking it.

**Review by keplerbb01 — APPROVED** [review]

**Comment by tresorama** [comment]
Cross-Issued on plain "splide" repo: 
https://github.com/Splidejs/splide/issues/1179

**Comment by sngazm** [comment]
This project appears to have stopped development. FYI, I'm using `patch-package` and `postinstall-postinstall` to automatically patch package.json to work around the problem.

**Comment by WenLonG12345** [comment]
I wish this can be merged immediately. Need this so badly. 
By the way is anyone knows about to do a `declare module` for this for current workaround until this is merged?

**Comment by JVrovetta** [comment]
Just waiting for merge... any reason why it hasn't been done yet?

**Comment by NeekoGta** [comment]
News? Dead project?

**Review by simovicaleksa — APPROVED** [review]
Fixes the issue, please merge.

**Review by ximple-dev — APPROVED** [review]

**Review by khakans — CHANGES_REQUESTED** [review]
please merge this fixing

**Comment by said-adibilarijani-syzygy** [comment]
Please merge this, it is important!

**Comment by akiri1199** [comment]
please merge this fixing

**Comment by websaid** [comment]
please merge this fixing

**Comment by P3DR0DEV** [comment]
10 months without responses from the maintainers, i'll close this pull request.

**Comment by nitlix** [comment]
Horrible stuff; a clear bug that goes into deployments experienced by every single person who uses spline with typescript not being fixed, when all it takes is one click to approve.

**Comment by websaid** [comment]
@NaotoshiFujita これメルグしてください

**Comment by shakibhasan09** [comment]
Is the maintainer abandoned this project? That's really sad

**Comment by pondorasti** [comment]
who's making a fork? 🌚

**Comment by nitlix** [comment]
> who's making a fork? 🌚

There already is one (;
https://github.com/patrickn2/react-splide

**Comment by thepraiz** [comment]
Just merge it 
It is 2024 already

**Comment by up2dul** [comment]
No wonder, the latest update to master was 2 years ago

**Pull request closed without merging**
